#!/bin/sh

### BEGIN INIT INFO
# Provides:          wvlmonitor
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Linkstation LS-WVL monitor script.
# Description:       
### END INIT INFO

#
# wvlmonitor: 
# - fix leds status
# - handle ls complete power-on
# - monitor power switch
# - monitor hdd temperature & control fan speed
# - monitor function button (todo)
#
# blstools - Tools for Buffalo Linkstation
# Copyright (C) 2010 Michele Manzato
#
# Credits:
# 	Thanks to archonfx on Buffalo NAS Central forum for HDD 
#	temperature monitoring command.
#
# Changelog:
#	Modified to work with a Debian kernel on an LS-WVL 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Load settings
. /etc/default/lsmonitor

# Location of pid file
PIDFILE=/var/run/lsmonitor.pid

# GPIO's for LS-WVL
GPIO_PWR_SW=46			# Power switch (power switch)
GPIO_AUT_SW=47			# Auto-Power switch (auto switch)
GPIO_FAN_STAT=43		# Fan low speed enable (fan lock)
GPIO_FAN_LO=17			# Fan low speed enable (fan low)
GPIO_FAN_HI=16			# Fan high speed enable (fan high)

GPIO_POWER_HDD0=8		# (pmx-power-hdd0)
GPIO_POWER_HDD1=9		# (pmx-power-hdd1)
GPIO_USB_VBUS=12		# (pmx-usb-vbus)
GPIO_FAN_HIGH=16		# (pmx-fan-high)
GPIO_FAN_LOW=17			# (pmx-fan-low)
GPIO_FAN_LOCK=43		# (pmx-fan-lock)
GPIO_FAN_HIGH=16		# (pmx-fan-high)
GPIO_LED_HDDERR0=34		# (pmx-led-hdderr0)
GPIO_LED_HDDERR1=35		# (pmx-led-hdderr1)
GPIO_LED_ALARM=36		# (pmx-led-alarm)
GPIO_LED_FUNC_RED=37	# (pmx-led-func_red)
GPIO_LED_FUNC_BLUE=39	# (pmx-led-func_blue)
GPIO_LED_INFO=38		# (pmx-led-info)
GPIO_LED_POWER=40		# (pmx-led-power)
GPIO_BTN_FUNC=45		# (pmx-btn-func)
GPIO_POWER_SW=46		# (pmx-power-sw)
GPIO_POWER_AUTOSW=47	# (pmx-power-autosw)

GPIO_LED_VALUE_ON=0   	# /sys/class/gpio/gpio$1/value
GPIO_LED_VALUE_OFF=1   	# /sys/class/gpio/gpio$1/value

gpio_config()
{
	if [ $1 = "enable" ]; then
		[ -d /sys/class/gpio/gpio$2 ] || echo $2 > /sys/class/gpio/export
		if [ $3 = "output" ]; then
			echo out > /sys/class/gpio/gpio$2/direction
		else
			echo in > /sys/class/gpio/gpio$2/direction
		fi
	else
		echo $2 > /sys/class/gpio/unexport
	fi
}


led_value()
{
	if [ $1 = "on" ]; then
		if [ -d /sys/class/gpio/gpio$2 ]; then
			echo ${GPIO_LED_VALUE_ON} > /sys/class/gpio/gpio$2/value
		else
			echo "can't found /sys/class/gpio/gpio$2 !!!"
		fi
	else
		echo ${GPIO_LED_VALUE_OFF} > /sys/class/gpio/gpio$2/value
	fi
}

enable_gpio()
{
	#gpio_config enable ${GPIO_PWR_SW} input
	#gpio_config enable ${GPIO_AUT_SW} input
	#gpio_config enable ${GPIO_FAN_STAT} input
	#gpio_config enable ${GPIO_FAN_LO} output
	gpio_config enable ${GPIO_LED_POWER} output
	gpio_config enable ${GPIO_LED_INFO} output
	gpio_config enable ${GPIO_LED_ALARM} output
	gpio_config enable ${GPIO_LED_FUNC_RED} output
	gpio_config enable ${GPIO_LED_FUNC_BLUE} output
	gpio_config enable ${GPIO_LED_HDDERR0} output
	gpio_config enable ${GPIO_LED_HDDERR1} output
}

disable_gpio()
{
	#gpio_config disable ${GPIO_PWR_SW}
	#gpio_config disable ${GPIO_AUT_SW}
	#gpio_config disable ${GPIO_FAN_STAT}
	#gpio_config disable ${GPIO_FAN_LO}
	#gpio_config disable ${GPIO_FAN_HI}
	gpio_config disable ${GPIO_LED_POWER} output
	gpio_config disable ${GPIO_LED_INFO} output
	gpio_config disable ${GPIO_LED_ALARM} output
	gpio_config disable ${GPIO_LED_FUNC_RED} output
	gpio_config disable ${GPIO_LED_FUNC_BLUE} output
	gpio_config disable ${GPIO_LED_HDDERR0} output
	gpio_config disable ${GPIO_LED_HDDERR1} output
}


fix_leds_status()
{
	led_value on ${GPIO_LED_POWER}
	led_value off ${GPIO_LED_INFO}
	led_value off ${GPIO_LED_ALARM}
	led_value off ${GPIO_LED_FUNC_RED}
	led_value off ${GPIO_LED_FUNC_BLUE}
	led_value off ${GPIO_LED_HDDERR0}
	led_value off ${GPIO_LED_HDDERR1}
}
# Monitor HDD temperature & control fan speed
monitor_temperature()
{
	#
	# Default settings for lsmonitor
	#
	# HDD temperature thresholds
	# HDDTEMP0=40
	# HDDTEMP1=45
	# HDDTEMP2=50
	#

	HDDCURRTEMP1=0

	HDDCURRTEMP2=0
	
	# Retrieve HDD temp
	# HDDTEMP=$(smartctl -d marvell /dev/sda --all -T permissive | grep "^194" | sed -re 's/^.* ([0-9]+)( .*)?$/\1/')
	# [ -b /dev/sda ] && HDDTEMP1=$(smartctl /dev/sda --all | awk '$1 = "194" {print $10}')
	# [ -b /dev/sdb ] && HDDTEMP2=$(smartctl /dev/sdb --all | awk '$1 = "194" {print $10}')
	[ -b /dev/sda ] && HDD_CURR_TEMP1=$(smartctl /dev/sda --all -T permissive | grep "^194" | awk '$1 = "194" {print $10}')
	[ -b /dev/sdb ] && HDD_CURR_TEMP2=$(smartctl /dev/sdb --all -T permissive | grep "^194" | awk '$1 = "194" {print $10}')

	
	# Get max temp
	if [ $HDD_CURR_TEMP1 -gt $HDD_CURR_TEMP2 ]; then
		HDDTEMP=$HDD_CURR_TEMP1
	else
		HDDTEMP=$HDD_CURR_TEMP2
	fi

	# Change fan speed accordingly
	if [ $HDDTEMP -le $HDDTEMP0 ] ; then
		# off
		echo 1 > /sys/class/gpio/gpio${GPIO_FAN_LO}/value
		echo 1 > /sys/class/gpio/gpio${GPIO_FAN_HI}/value
	elif [ $HDDTEMP -le $HDDTEMP1 ] ; then
		# slow
		echo 0 > /sys/class/gpio/gpio${GPIO_FAN_LO}/value
		echo 1 > /sys/class/gpio/gpio${GPIO_FAN_HI}/value
	elif [ $HDDTEMP -le $HDDTEMP2 ] ; then
		# medium
		echo 1 > /sys/class/gpio/gpio${GPIO_FAN_LO}/value
		echo 0 > /sys/class/gpio/gpio${GPIO_FAN_HI}/value
	else
		# fast
		echo 0 > /sys/class/gpio/gpio${GPIO_FAN_LO}/value
		echo 0 > /sys/class/gpio/gpio${GPIO_FAN_HI}/value
	fi
}


# Control LS switch status to power down the unit
lsmonitor_daemon()
{
	COUNT=20
	while [ true ] ; do
		# Check switch status
		PWR_SW=`cat /sys/class/gpio/gpio${GPIO_PWR_SW}/value`
		AUT_SW=`cat /sys/class/gpio/gpio${GPIO_AUT_SW}/value`

		# Terminate when in OFF state
		if [ "$PWR_SW" -eq 1 ] && [ "$AUT_SW" -eq 1 ]; then
			break
		fi

		# Once per minute monitor HDD temperature
		if [ $COUNT -eq 20 ] ; then
			COUNT=0
			monitor_temperature
		else
			COUNT=$(( $COUNT + 1 ))
		fi

		sleep 3
		
	done

	# Run the fan at low speed while halting, just in case halt hangs the unit
	echo 0 > /sys/class/gpio/gpio${GPIO_FAN_LO}/value
	echo 1 > /sys/class/gpio/gpio${GPIO_FAN_HI}/value

	# blink power led
	#echo timer > /sys/devices/platform/leds-gpio/leds/power/trigger
	#echo   100 > /sys/devices/platform/leds-gpio/leds/power/delay_on
	#echo   100 > /sys/devices/platform/leds-gpio/leds/power/delay_off
	
	# Initiate unit shutdown
	halt
}

# Kill the lsmonitor daemon
kill_lsmonitor_daemon()
{
        PID=`cat $PIDFILE`
	if [ "$PID" != "" ] ; then
        	kill $PID
		rm $PIDFILE
	fi
}


case $1 in
	start)
		# Enable the corresponding GPIO's
		enable_gpio

		# Fix leds to normal status.
		fix_leds_status
		
		# Start the lsmonitor daemon
		lsmonitor_daemon &
	        echo $! > $PIDFILE
  		;;
	stop)
		# Kill the lsmonitor daemon
		kill_lsmonitor_daemon

		# Disable the corresponding GPIO's
		disable_gpio
  		;;

	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;

	*)
		echo "Usage: $0 {start|stop|restart|force-reload}"
		exit 2
		;;
esac
